# Spec-Kit Integration Configuration for Guardian Agents
# This file defines how Guardian agents integrate with spec-kit for spec-driven development

spec_kit_version: ">=1.0.0"
guardian_integration_version: "1.0.0"

# Agent to Spec Type Mappings
agent_spec_mappings:
  # Strategy & Product Agents
  "001-strategy-product-leadership-guardian":
    generates: ["product-vision-spec", "roadmap-spec", "strategy-spec"]
    consumes: ["market-analysis-spec", "user-research-spec"]
    workflow: "product_strategy"

  "002-strategy-product-strategy-guardian":
    generates: ["feature-spec", "requirements-spec", "acceptance-criteria-spec"]
    consumes: ["product-vision-spec", "user-story-spec"]
    workflow: "feature_definition"

  # Architecture Agents
  "044-architecture-principal-architect-guardian":
    generates: ["system-architecture-spec", "api-contract-spec", "data-model-spec"]
    consumes: ["requirements-spec", "technical-constraints-spec"]
    workflow: "system_design"

  "045-architecture-senior-architect-guardian":
    generates: ["component-spec", "integration-spec", "deployment-spec"]
    consumes: ["system-architecture-spec", "performance-requirements-spec"]
    workflow: "detailed_design"

  # Backend Development Agents
  "061-development-backend-director-guardian":
    generates: ["backend-architecture-spec", "database-schema-spec", "api-design-spec"]
    consumes: ["system-architecture-spec", "data-model-spec"]
    workflow: "backend_architecture"

  "062-development-backend-senior-guardian":
    generates: ["api-implementation-spec", "database-migration-spec", "service-spec"]
    consumes: ["api-contract-spec", "database-schema-spec"]
    workflow: "backend_implementation"

  # Frontend Development Agents
  "064-development-frontend-director-guardian":
    generates: ["frontend-architecture-spec", "component-library-spec", "ui-routing-spec"]
    consumes: ["api-contract-spec", "design-system-spec"]
    workflow: "frontend_architecture"

  "065-development-frontend-senior-guardian":
    generates: ["component-implementation-spec", "state-management-spec", "ui-integration-spec"]
    consumes: ["component-library-spec", "api-implementation-spec"]
    workflow: "frontend_implementation"

  # Quality Engineering Agents
  "071-development-quality-director-guardian":
    generates: ["test-strategy-spec", "quality-gates-spec", "automation-framework-spec"]
    consumes: ["requirements-spec", "system-architecture-spec"]
    workflow: "quality_strategy"

  "072-development-quality-senior-guardian":
    generates: ["test-plan-spec", "test-case-spec", "automation-spec"]
    consumes: ["feature-spec", "api-contract-spec"]
    workflow: "test_implementation"

  # DevOps & Infrastructure Agents
  "081-infrastructure-devops-director-guardian":
    generates: ["infrastructure-spec", "deployment-pipeline-spec", "monitoring-spec"]
    consumes: ["deployment-spec", "scalability-requirements-spec"]
    workflow: "infrastructure_design"

  "082-infrastructure-devops-senior-guardian":
    generates: ["ci-cd-spec", "environment-spec", "automation-spec"]
    consumes: ["infrastructure-spec", "deployment-pipeline-spec"]
    workflow: "deployment_automation"

# Spec-driven Workflows
workflows:
  product_strategy:
    description: "Product strategy and vision development"
    agents: ["001", "002"]
    input_specs: ["market-analysis-spec"]
    output_specs: ["product-vision-spec", "feature-spec"]
    estimated_duration: "1-2 days"

  system_design:
    description: "System architecture and design"
    agents: ["044", "045"]
    input_specs: ["requirements-spec", "product-vision-spec"]
    output_specs: ["system-architecture-spec", "component-spec"]
    estimated_duration: "2-3 days"

  feature_development:
    description: "End-to-end feature development"
    agents: ["002", "044", "062", "065", "072"]
    input_specs: ["user-story-spec"]
    output_specs: ["feature-implementation-spec", "test-plan-spec"]
    estimated_duration: "3-5 days"

  api_development:
    description: "API design and implementation"
    agents: ["044", "062", "072"]
    input_specs: ["api-requirements-spec"]
    output_specs: ["api-contract-spec", "api-implementation-spec", "api-test-spec"]
    estimated_duration: "2-3 days"

  deployment_pipeline:
    description: "CI/CD and deployment setup"
    agents: ["081", "082", "092"]
    input_specs: ["deployment-requirements-spec"]
    output_specs: ["ci-cd-spec", "infrastructure-spec", "security-spec"]
    estimated_duration: "1-2 days"

# Spec Templates for Agent Generation
spec_templates:
  api-contract-spec:
    template: |
      # API Contract Specification

      ## Overview
      Generated by: {{agent_name}}
      Date: {{generation_date}}

      ## Endpoints
      {{#endpoints}}
      ### {{method}} {{path}}
      **Description**: {{description}}

      **Request**:
      ```json
      {{request_schema}}
      ```

      **Response**:
      ```json
      {{response_schema}}
      ```
      {{/endpoints}}

      ## Data Models
      {{data_models}}

      ## Authentication
      {{auth_requirements}}

      ## Error Handling
      {{error_handling}}

    validation:
      required_fields: ["endpoints", "data_models"]
      format: "markdown"

  system-architecture-spec:
    template: |
      # System Architecture Specification

      ## Overview
      Generated by: {{agent_name}}
      Date: {{generation_date}}

      ## Architecture Diagram
      ```mermaid
      {{architecture_diagram}}
      ```

      ## Components
      {{#components}}
      ### {{name}}
      **Responsibility**: {{responsibility}}
      **Technology**: {{technology}}
      **Dependencies**: {{dependencies}}
      {{/components}}

      ## Data Flow
      {{data_flow_description}}

      ## Scalability Considerations
      {{scalability_notes}}

      ## Security Requirements
      {{security_requirements}}

    validation:
      required_fields: ["components", "data_flow_description"]
      format: "markdown"

# Integration Commands
commands:
  sync_specs:
    description: "Synchronize Guardian agents with spec-kit specifications"
    command: "gpm sync-specs"
    options:
      - "--agent": "Sync specific agent only"
      - "--workflow": "Sync entire workflow"
      - "--dry-run": "Show what would be synced without applying changes"

  generate_from_spec:
    description: "Generate agent content from existing specifications"
    command: "gpm generate-from-spec <spec-file>"
    options:
      - "--agent": "Target specific agent for generation"
      - "--template": "Use specific template for generation"

  validate_integration:
    description: "Validate spec-kit integration setup"
    command: "gpm validate-specs"
    checks:
      - "spec-kit installation"
      - "spec directory structure"
      - "agent-spec mappings"
      - "template availability"

# File Structure Integration
file_structure:
  specs_directory: "specs/"
  agent_specs: "specs/agents/"
  workflow_specs: "specs/workflows/"
  generated_docs: "specs/generated/"

  naming_conventions:
    agent_spec: "{{agent_id}}-{{spec_type}}-spec.md"
    workflow_spec: "{{workflow_name}}-workflow-spec.md"
    generated_doc: "{{agent_id}}-{{timestamp}}-generated.md"

# Automation Rules
automation:
  auto_sync:
    enabled: true
    triggers:
      - "agent_update"
      - "spec_change"
    frequency: "on_change"

  auto_validation:
    enabled: true
    on: ["spec_generation", "agent_update"]

  auto_documentation:
    enabled: true
    generates: ["workflow_docs", "integration_guide"]

# Development Integration
development:
  ide_integration:
    vscode_extension: "spec-kit.guardian-integration"
    file_associations:
      - "*.spec.md": "spec-kit"
      - "*-guardian.md": "guardian-agent"

  git_hooks:
    pre_commit: "gpm validate-specs"
    post_merge: "gpm sync-specs --auto"

  build_integration:
    npm_scripts:
      "spec:sync": "gpm sync-specs"
      "spec:validate": "gpm validate-specs"
      "spec:generate": "gpm generate-from-spec specs/**/*.md"
